1-UI/Job.Fac.Ui.Web/Models/ContatoModeloVisao.cs
using System;

namespace Job.Fac.Ui.Web.Models
{
    public class ContatoModeloVisao
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    }
}

1-UI/Job.Fac.Ui.Web/Controllers/ContatoController.cs
using Job.Fac.Bll.Modelo.Candidato.Contato;
using System.Web.Mvc;
using Job.Fac.Bll.Nucleo.Fabrica;
using Job.Fac.Ui.Web.Models;
using AutoMapper;

namespace Job.Fac.Ui.Web.Controllers
{
    public class ContatoController : Job.Fac.Ui.Nucleo.Mvc.Base.BaseControlador<Contato,ContatoModeloVisao>
    {
        public ContatoController(IBllFabrica bllFabrica,IMapper mapeador) : base(bllFabrica,mapeador)
        {
        }

        // GET: Contato
        public ActionResult Index()
        {
            return View();
        }

        protected override Contato MapearModeloVisaoParaModeloBll(ContatoModeloVisao o)
        {
            return new Contato(o.Nome, o.Telefone, o.Email, bllFabrica.ServicoContexto);
        }
    }
}

1-UI/Job.Fac.Ui.Web/Views/Contato/Index.cshtml
@model Job.Fac.Ui.Web.Models.ContatoModeloVisao

@{
    ViewBag.Title = "Deixe seu contato.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="ui teal image header">
    <!-- <img class="image" src="assets/images/logo.png">-->
    <div class="content">
        Quero receber mais informações!
    </div>
</h2>
@using (Html.BeginForm("Registrar", "Contato", FormMethod.Post, new { @class = "ui large form" }))
{
    <div class="ui stacked segment">
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "" })
        <div class="field">
            <div class="ui left icon input">
                <i class="lock icon"></i>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @placeholder = "Nome e sobrenome" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "" })
            </div>
        </div>
        <div class="field">
            <div class="ui left icon input">
                <i class="lock icon"></i>
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @placeholder = "Telefone" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "" })
            </div>
        </div>


        <div class="field">
            <div class="ui left icon input">
                <i class="lock icon"></i>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @placeholder = "E-mail" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "" })
            </div>

        </div>
        <div class="field">
            <button class="ui fluid teal ui button" type="submit">Enviar</button>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/semantic-ui")
}

1-UI/Job.Fac.Ui.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>@ViewBag.Titulo</title>

    @Styles.Render("~/Content/css")
</head>
<body>

    <style type="text/css">
        body {
            background-color: #DADADA;
        }

            body > .grid {
                height: 100%;
            }

        .image {
            margin-top: -100px;
        }

        .column {
            max-width: 450px;
        }
    </style>
    <script>
        $(document)
        .ready(function () {
            $('.ui.form')
            .form({
                fields: {
                    email: {
                        identifier: 'email',
                        rules: [
                        {
                            type: 'empty',
                            prompt: 'Please enter your e-mail'
                        },
                        {
                            type: 'email',
                            prompt: 'Please enter a valid e-mail'
                        }
                        ]
                    },
                    password: {
                        identifier: 'password',
                        rules: [
                        {
                            type: 'empty',
                            prompt: 'Please enter your password'
                        },
                        {
                            type: 'length[6]',
                            prompt: 'Your password must be at least 6 characters'
                        }
                        ]
                    }
                }
            })
            ;
        })
        ;
    </script>
    <div class="ui middle aligned center aligned grid">
        <div class="column">

            @RenderBody()
            
            @if (ViewBag.Mensagens != null)
            {

                foreach (Job.Fac.Ui.Nucleo.Mensagem mensagem in ViewBag.Mensagens)
                {
                    if (mensagem.TipoDeMensagem == Job.Fac.Ui.Nucleo.Enum.TipoDeMensagens.Erro)
                    {
                        <div class="ui error message">
                            @mensagem
                        </div>
                    }
                    if (mensagem.TipoDeMensagem == Job.Fac.Ui.Nucleo.Enum.TipoDeMensagens.Sucesso)
                    {
                        <div class="ui success message">
                            <i class="close icon"></i>
                            <div class="header">Registrado! </div>
                            <p>@mensagem</p>
                        </div>
                    }
                }
            }
            <footer>
                <p>&copy; @DateTime.Now.Year - codeteamsoft</p>
            </footer>
        </div>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>